Ensure that `dataset` exists when reading `tags` (#628)
Previously this statement was outside the `ctx` context, and so `dataset` may already have been freed before we call `dataset.tags()`. In my experience, this was sporadically leading to either of the following errors:

```
rasterio.errors.RasterioIOError: Dataset is closed`
```

or 

```
rasterio._err.ObjectNullError: Pointer 'hObject' is NULL in 'GDALGetMetadata'.
```