change arguments
The argument  ("tile", {"z": "{z}", "x": "{x}", "y": "{y}"}) causes errors below.

File "/home/ubuntu/app/app.py", line 48, in tilejson
    tile_url = request.url_for("tile", {"z": "{z}", "x": "{x}", "y": "{y}"})
TypeError: HTTPConnection.url_for() takes 2 positional arguments but 3 were given

("tile", z='{z}', x='{x}', y='{y}') is correct.