rio-tiler V5.0 (#616)
* update readme

* PER_BAND mask and MaskedArray (#580)

* sketch use of MaskedArray with PER_BAND mask

* update PointData and fix tests

* update mosaics

* update nodata mask

* remove unused

* update changelog

* migration guide

* split resampling option to RasterIO and Warp options (#590)

* refactor Mask tests and Benchmark

* refactor Mask tests and Benchmark (#591)

* change arguments in dynamic_tiler.md (#592)

* change arguments

The argument  ("tile", {"z": "{z}", "x": "{x}", "y": "{y}"}) causes errors below.

File "/home/ubuntu/app/app.py", line 48, in tilejson
    tile_url = request.url_for("tile", {"z": "{z}", "x": "{x}", "y": "{y}"})
TypeError: HTTPConnection.url_for() takes 2 positional arguments but 3 were given

("tile", z='{z}', x='{x}', y='{y}') is correct.

* Update docs/src/advanced/dynamic_tiler.md

---------

Co-authored-by: Vincent Sarago <vincent.sarago@gmail.com>

* refactor MosaicMethods (#594)

* refactor MosaicMethods

* fix tests

* Optional boto3 (#597)

* make boto3 an optional dependency

* update migration

* update test dependencies

* add flake8 rules in ruff (#600)

* update dev version

* update mosaic example notebook custom pixel_selection class (#602)

* improve cutline handling (#598)

* Improve cutline handling

Closes #588

* handle projection

---------

Co-authored-by: vincentsarago <vincent.sarago@gmail.com>

* remove useless cache

* save benchmarks

* add benchmarking in docs

* fix nodata/mask/alpha forwarding for GCPS dataset (#604)

* remove boto3

* Allow clip-box to auto expand (#608)

* Allow clip-box to auto expand

* Add test

* Update tests/test_io_xarray.py

* Fix import order

* Changes from black linter

* Change default to true

* use auto_expand in part and update changelog

---------

Co-authored-by: Vincent Sarago <vincent.sarago@gmail.com>

* allow morecantile 4.0 (#606)

* allow morecantile 4.0

* set morecantile min version to 4.0

* update changelog

* forward statistics from STAC raster:bands (#611)

* forward statistics from STAC raster:bands

* forward tags as metadata and forward metadata when creating ImageData from list

* update changelog

* handle nodata in XarrayReader (#612)

* handle nodata in XarrayReader

* update changelog

* add AWS credential overrides for S3 stac (#613)

* add AWS credential overrides for S3 stac

* catch warnings

* deprecated model methods (#615)

* update readme

---------

Co-authored-by: TTY6335 <36815385+TTY6335@users.noreply.github.com>
Co-authored-by: Daniel Wiesmann <yellowcap@users.noreply.github.com>
Co-authored-by: Aimee Barciauskas <aimee@developmentseed.org>